name: flutter_counter
description: A new Flutter application.
version: 1.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.2.0
  sqflite: ^1.1.6+3
  shared_preferences: ^0.5.3+4
  flutter_slidable: ^0.5.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true